#services:
#  db:
#    image: postgres:16
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
#      POSTGRES_DB: messages_db
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    secrets:
#      - db_password
#
#  app:
#    build: .
#    depends_on:
#      - db
#    ports:
#      - "8000:8000"
#    environment:
#      API_KEY_FILE: /run/secrets/api_key
#      DB_PASSWORD_FILE: /run/secrets/db_password
#    secrets:
#      - api_key
#      - db_password
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
#
#  tests:
#    build: .
#    depends_on:
#      - db
#    environment:
#      API_KEY_FILE: /run/secrets/api_key
#      DB_PASSWORD_FILE: /run/secrets/db_password
#    secrets:
#      - api_key
#      - db_password
#    command: sh -c "sleep 15 && pytest -v"
#
#volumes:
#  postgres_data:
#
#secrets:
#  api_key:
#    file: ./secrets/api_key.txt
#  db_password:
#    file: ./secrets/db_password.txt
version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: messages_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_password
    networks:
      - app_network

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      API_KEY_FILE: /run/secrets/api_key
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - api_key
      - db_password
    command: ["/wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - app_network

  tests:
    build: .
    depends_on:
      - db
    environment:
      API_KEY_FILE: /run/secrets/api_key
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - api_key
      - db_password
    command: sh -c "pytest -v -s"
    networks:
      - app_network

volumes:
  postgres_data:

secrets:
  api_key:
    file: ./secrets/api_key.txt
  db_password:
    file: ./secrets/db_password.txt

networks:
  app_network:
    external: true

