services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile.chat
    ports:
      - "8100:8100"
    environment:
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
      API_KEY_FILE: /run/secrets/api_key
      API_BASE_URL: "http://app:8000"
    secrets:
      - openai_api_key
      - api_key
    networks:
      - app_network
    depends_on:
      - app

secrets:
  openai_api_key:
    file: secrets/openai_api_key.txt
  api_key:
    file: secrets/api_key.txt

networks:
  app_network:
    external: true
